image: Visual Studio 2017

environment:
#use MINGW64 environment to have native WIndows  binaries
  MSYSTEM: MINGW64 
#run bash without changing current directory
  CHERE_INVOKING: 1
  
install:
  - C:\msys64\usr\bin\bash --login -c "pacman --needed --noconfirm -S texinfo autoconf automake mingw-w64-x86_64-make mingw-w64-x86_64-gcc mingw-w64-x86_64-ncurses"
  
build_script:
#run command via bash --login to have all env variables set up
  - C:\msys64\usr\bin\bash --login -c "echo Build using $(expr $(nproc) + 1) jobs"
  - C:\msys64\usr\bin\bash --login -c "make -j$(expr $(nproc) + 1)"
  
on_failure:
  - ECHO Printing distrib\MinGW64-error.log...
  - TYPE distrib\MinGW64-error.log

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
