image: Visual Studio 2017

environment:
  MSYSTEM: MINGW64

install:
  - SET PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - SET PATH=C:\msys64\usr\bin;%PATH%
  - pacman --needed --noconfirm -S texinfo autoconf automake mingw-w64-x86_64-make mingw-w64-x86_64-gcc
  
build_script:
  - make

on_failure:
  - ECHO Printing distrib\MinGW64-error.log...
  - TYPE distrib\MinGW64-error.log

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
