image: Visual Studio 2017

environment:
  matrix:
  - MSYSTEM: CYGWIN64
    PATH: /bin:/usr/bin:/usr/local/bin
  - MSYSTEM: MINGW64
    PATH: C:\msys64\usr\bin\;C:\msys64\bin
#run bash without changing current directory
  CHERE_INVOKING: 1
  
install:
#  - bash --login -c "pacman --needed --noconfirm -S texinfo autoconf automake mingw-w64-x86_64-make mingw-w64-x86_64-gcc"
  
build_script:
  - bash --login -c "echo Build using $(expr $(nproc) + 1) jobs"
  - bash --login -c "make -j$(expr $(nproc) + 1)"
  
on_failure:
  - "tail distrib/*64-error.log"

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
