image: Visual Studio 2017

environment:
  matrix:
    - TARGET: MINGW64
      #use MINGW64 environment to have native Windows binaries
      PATH: C:\MinGW\bin;
    - TARGET: Cygwin64
      #use Cygwin64 environment
      PATH: C:\Cygwin64\bin;
#run bash without changing current directory
  CHERE_INVOKING: 1
  
install:
#  - C:\msys64\usr\bin\bash --login -c "pacman --needed --noconfirm -S texinfo autoconf automake mingw-w64-x86_64-make mingw-w64-x86_64-gcc"
  
build_script:
  - "echo Build using $(expr $(nproc) + 1) jobs"
  - C:\msys64\usr\bin\bash --login -c "make -j$(expr $(nproc) + 1)"
  
on_failure:
  - "tail distrib/*64-error.log"

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
