image: Visual Studio 2017

environment:
  matrix:
  - MSYSTEM: Cygwin64
    PATH: C:\msys64\usr\bin
    BUILD: Cygwin64
  - MSYSTEM: MINGW64
    PATH: C:\msys64\usr\bin
    BUILD: Mingw64
#run bash without changing current directory
  CHERE_INVOKING: 1

build_script:
  - bash --login -c "make -j$(expr $(nproc) + 3)"
  - bash --login -c "cp distrib/*xtensa-lx106-elf.tar.gz ."

on_failure:
  - bash --login -c "tail -n100 distrib/$BUILD*.log"

artifacts:
  - path: 'distrib/$BUILD*.log'
    name: logs
    type: zip
  - path: '*xtensa-lx106-elf.tar.gz'
    name: distribution

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
